baseURL = 'https://fuka.one'
languageCode = 'en-us'
title = 'Fuka Network'
description = '風花ネットワーク'
theme = 'pulp'
canonifyurls = true
hasCJKLanguage = true
copyright = "2023-2025 Fuka Network"

[params]
    avatar = "logo.png"
    description = '風花ネットワーク'

[[menu.main]]
    identifier = "github"
    # name = "GitHub"
    pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/FukaNet"
    weight = 30

[[menu.main]]
    identifier = "email"
    # name = "Email"
    pre = "<i class='fa fa-envelope fa-lg'></i>"
    url = "mailto:dev@fuka.one"
    weight = 40
